# Generated by Django 4.0.4 on 2022-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_tag_historicaltag_historicalcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Показать всем'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Показать всем'),
        ),
    ]
