# Generated by Django 4.0.4 on 2022-05-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_article_visible_historicalarticle_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalarticle',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltag',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='HistoricalArticle',
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
        migrations.DeleteModel(
            name='HistoricalTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
